### ISSUE TITLE
Will you be nice to upload your paper as documention?

### ISSUE THREAD

**Issue by suijingfeng** [raady07/CNN-for-bearing-fault-diagnosis#1]
Need the paper to understand the code, thank you.

**Comment by shahmustafa** [comment]
[https://www.researchgate.net/publication/320475812_Speed_Invariant_Bearing_Fault_Characterization_Using_Convolutional_Neural_Networks](url) Need to request

**Comment by suijingfeng** [comment]
thanks，i am no longer working at this field.
